name: Build and Publish Extensions

on:
    push:
        branches: [master]

jobs:
    build_and_publish:
        name: Setup Linux environment
        runs-on: ubuntu-latest

        env:
            # Add the names of the extension's folders that were created with spicetify-creator and need to be built with GitHub Actions
            FOLDERS: "Play-on-YouTube"

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Create dist folder
              run: mkdir dist

            - name: Build extensions
              run: |
                  for folder in $FOLDERS; do
                    cd $folder
                    mkdir $folder
                    npm ci
                    npm run build-local
                    mv -f dist/* $folder
                    mv -f assets/preview* $folder
                    mv -f README.md $folder
                    mv -f $folder ../dist
                    cd ..
                  done

            - name: Move License and Readme.md
              run: mv -f README.md LICENSE dist/

            - name: Publish extensions
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist
                  FOLDER: "dist"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
