name: Build and Publish Extensions

on:
    push:
        branches: [master]

jobs:
    build_and_publish:
        name: Setup Linux environment
        runs-on: ubuntu-latest

        env:
            FOLDERS: "Play-on-YouTube"

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Build extensions
              run: |
                  for folder in $FOLDERS; do
                    cd $folder
                    npm ci
                    npm run build-local
                    ls
                    cd dist
                    cd ..
                    cd ..
                  done

            - name: Publish extensions
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist
                  FOLDER: "dist"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
