name: Build and Publish Extensions

on:
    push:
        paths:
            - README.md
            - LICENSE
            # - Play-on-YouTube/**
            - "**/tsconfig.json"
    pull_request:
        paths:
            - README.md
            - LICENSE
            - Play-on-YouTube/**

jobs:
    build_and_publish:
        name: Setup Linux environment
        runs-on: ubuntu-latest

        env:
            FOLDERS: "Play-on-YouTube"

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install repository dependencies
              run: npm ci

            - name: Create publish folder
              run: mkdir publish

            - name: Build extensions
              run: |
                  for folder in $FOLDERS; do
                    cd $folder
                    mkdir $folder
                    npm ci
                    npm run build-local
                    mv -f dist/* $folder
                    mv -f assets/preview* $folder
                    mv -f README.md $folder
                    mv -f $folder ../publish
                    cd ..
                  done

            - name: Move License and Readme.md
              run: mv -f README.md LICENSE publish/

            - name: Publish extensions
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist
                  FOLDER: "publish"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
