name: Build and Publish Extensions

on:
    push:
        branches:
            - master
        paths:
            - "Play-on-YouTube/**"

jobs:
    build_and_publish:
        name: Setup Linux environment
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Build project
              run: |
                  if [[ ${{ github.event_name }} == 'push' ]]; then
                      extension_name=$(basename "${{ github.event.path }}")
                      cd "${{ github.workspace }}/${{ github.event.path }}"
                      echo "${{ github.workspace }}/${{ github.event.path }}"
                      echo "${{ github.workspace }}/${extension_name}"
                      pwd
                      npm install
                      npm run build-local

                      # Publish build to dist branch
                      uses: s0/git-publish-subdir-action@develop
                      with:
                          branch: dist
                          folder: "dist-${{ github.event.path }}"
                          remote: origin
                          github_token: ${{ secrets.GITHUB_TOKEN }}
                  fi
